author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2024-07-15
description = K-nearest neighbor regression and classification
tags = C14 C38
min-version = 2024a
public = knn_fit knn_predict knn_scores knn_summary knn_plot_score knn_plot_cvscores knn_gui_control
help = knn_help.md
sample-script = knn_sample.inp
depends = extra CvDataSplitter
gui-main = knn_gui_control
menu-only = knn_gui_control
label = KNN regression + classification
menu-attachment = MAINWIN/Model/RobustModels
